### ISSUE TITLE
能否HOOK动态加载的DEX？

### ISSUE THREAD

**Issue by koangel** [bmax121/BudHook#4]
比如A.APK在运行中以DEXCLASSLOADER的方式加载了B.APK，然后又通过DEXCLASSLOADER加载C.APK，而我要HOOK的函数在C.APK中，我如何能HOOK到呢？

**Comment by bmax121** [comment]
@koangel 只要能拿到classloader，能找到这个类就能 hook，可能需要你改改代码

**Comment by koangel** [comment]
解决了，我关了，直接HOOK的DEXCLASSLOADER构造函数
